
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author utkut
 */
public class Calculator extends javax.swing.JFrame {

    static int anaSayi;
    static int islem;
    static int yeniSayiInt;
    static String[] islemDizisi = new String[2];
    static String yeniSayi;
    static boolean ustuneYaz = false;
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        AnaLabel.setText("0");
        IslemLabel.setText(" ");
    }
    
    private void sayiSetText(int sayi){
        AnaLabel.setText(String.valueOf(sayi));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        YuzdeButton = new javax.swing.JButton();
        CEButton = new javax.swing.JButton();
        CButton = new javax.swing.JButton();
        SilButton = new javax.swing.JButton();
        ArtiButton = new javax.swing.JButton();
        EsittirButton = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ArtiEksiButton = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        EksiButton = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        BolButton = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        CarpButton = new javax.swing.JButton();
        AnaLabel = new javax.swing.JLabel();
        IslemLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Utku Berken Tekinsoy");

        YuzdeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        YuzdeButton.setText("%");

        CEButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CEButton.setText("CE");
        CEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEButtonActionPerformed(evt);
            }
        });

        CButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CButton.setText("C");
        CButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CButtonActionPerformed(evt);
            }
        });

        SilButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SilButton.setText("<-");
        SilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilButtonActionPerformed(evt);
            }
        });

        ArtiButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ArtiButton.setText("+");
        ArtiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtiButtonActionPerformed(evt);
            }
        });

        EsittirButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EsittirButton.setText("=");
        EsittirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsittirButtonActionPerformed(evt);
            }
        });

        Button0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ArtiEksiButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ArtiEksiButton.setText("+/-");
        ArtiEksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtiEksiButtonActionPerformed(evt);
            }
        });

        Button1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        EksiButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EksiButton.setText("-");
        EksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EksiButtonActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button6.setText("6");
        Button6.setToolTipText("");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        BolButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BolButton.setText("/");
        BolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolButtonActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        CarpButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CarpButton.setText("*");
        CarpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarpButtonActionPerformed(evt);
            }
        });

        AnaLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        AnaLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        IslemLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IslemLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ArtiEksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EsittirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ArtiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AnaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(YuzdeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IslemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(IslemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AnaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YuzdeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CarpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArtiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ArtiEksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EsittirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getAccessibleContext().setAccessibleName("Utku Berken Tekinsoy");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArtiEksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtiEksiButtonActionPerformed
        anaSayi = Integer.valueOf(AnaLabel.getText()) * -1;
        sayiSetText(anaSayi);
    }//GEN-LAST:event_ArtiEksiButtonActionPerformed

    private void CButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonActionPerformed
        sayiSetText(0);
        IslemLabel.setText(" ");
    }//GEN-LAST:event_CButtonActionPerformed

    private void CEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEButtonActionPerformed
        if (String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("+") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("-") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("/") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("*")) {
            AnaLabel.setText("0");
            return;
        }
        if (IslemLabel.getText().contains("+")) {
            islemDizisi = IslemLabel.getText().split("\\+");
            if (Integer.valueOf(islemDizisi[0]) + Integer.valueOf(islemDizisi[1]) == Integer.valueOf(AnaLabel.getText())) {
                IslemLabel.setText(" ");
            }
        } else if(IslemLabel.getText().contains("/")) {
            islemDizisi = IslemLabel.getText().split("/");
            if (Integer.valueOf(islemDizisi[0]) / Integer.valueOf(islemDizisi[1]) == Integer.valueOf(AnaLabel.getText())) {
                IslemLabel.setText(" ");
            }
        } else if(IslemLabel.getText().contains("-")) {
            islemDizisi = IslemLabel.getText().split("-");
            if (Integer.valueOf(islemDizisi[0]) - Integer.valueOf(islemDizisi[1]) == Integer.valueOf(AnaLabel.getText())) {
                IslemLabel.setText(" ");
            }
        }
        else if(IslemLabel.getText().contains("*")) {
            islemDizisi = IslemLabel.getText().split("\\*");
            if (Integer.valueOf(islemDizisi[0]) * Integer.valueOf(islemDizisi[1]) == Integer.valueOf(AnaLabel.getText())) {
                IslemLabel.setText(" ");
            }
        }
            AnaLabel.setText("0");
        
    }//GEN-LAST:event_CEButtonActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) {
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) {
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "1");
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) {
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "2");
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) {
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) {
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) {
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) {
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) {
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) { 
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "8");
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        if (ustuneYaz) {
            AnaLabel.setText("");
            ustuneYaz = false;
        }
        if (AnaLabel.getText().equals("0")) {
            AnaLabel.setText("");
        }
        if(AnaLabel.getText().length() == 8) {
            return;
        }
        AnaLabel.setText(AnaLabel.getText() + "9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void SilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilButtonActionPerformed
        yeniSayi = "";
        for (int i = 0; i < AnaLabel.getText().length() - 1; i++) {
            yeniSayi += AnaLabel.getText().charAt(i);
        }
        if (yeniSayi.equals("")) {
            AnaLabel.setText("0");
            return;
        }
        AnaLabel.setText(yeniSayi);
    }//GEN-LAST:event_SilButtonActionPerformed

    private void ArtiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtiButtonActionPerformed
        if (String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("+") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("-") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("/") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("*")) {
            yeniSayi = "";
            for (int i = 0; i < IslemLabel.getText().length() - 1; i++) {
            yeniSayi += IslemLabel.getText().charAt(i);
            }
        }
        IslemLabel.setText(AnaLabel.getText() + "+");
        ustuneYaz = true;
    }//GEN-LAST:event_ArtiButtonActionPerformed

    private void EksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EksiButtonActionPerformed
        if (String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("+") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("-") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("/") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("*")) {
            yeniSayi = "";
            for (int i = 0; i < IslemLabel.getText().length() - 1; i++) {
            yeniSayi += IslemLabel.getText().charAt(i);
            }
        }
        IslemLabel.setText(AnaLabel.getText() + "-");
        ustuneYaz = true;
    }//GEN-LAST:event_EksiButtonActionPerformed

    private void BolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolButtonActionPerformed
        if (String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("+") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("-") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("/") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("*")) {
            yeniSayi = "";
            for (int i = 0; i < IslemLabel.getText().length() - 1; i++) {
            yeniSayi += IslemLabel.getText().charAt(i);
            }
        }
        IslemLabel.setText(AnaLabel.getText() + "/");
        ustuneYaz = true;
    }//GEN-LAST:event_BolButtonActionPerformed

    private void CarpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarpButtonActionPerformed
        if (String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("+") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("-") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("/") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("*")) {
            yeniSayi = "";
            for (int i = 0; i < IslemLabel.getText().length() - 1; i++) {
            yeniSayi += IslemLabel.getText().charAt(i);
            }
        }
        IslemLabel.setText(AnaLabel.getText() + "*");
        ustuneYaz = true;
    }//GEN-LAST:event_CarpButtonActionPerformed

    private void EsittirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsittirButtonActionPerformed
        if (IslemLabel.getText().contains("+") || IslemLabel.getText().contains("-") ||
                IslemLabel.getText().contains("/") ||IslemLabel.getText().contains("*")) {
            if (String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("+") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("-") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("/") ||
                String.valueOf(IslemLabel.getText().charAt(IslemLabel.getText().length() - 1)).equals("*")) {
                
                if(IslemLabel.getText().contains("*")) {
                    yeniSayi = "";
            for (int i = 0; i < IslemLabel.getText().length() - 1; i++) {
            yeniSayi += IslemLabel.getText().charAt(i);
            }
                    if (yeniSayi.length() > 8 || yeniSayiInt > 99999999) {
                        return;
                    }
            IslemLabel.setText(yeniSayi+ "*" + AnaLabel.getText() );
            islemDizisi = IslemLabel.getText().split("\\*");
            yeniSayiInt = Integer.valueOf(islemDizisi[0]) * Integer.valueOf(islemDizisi[1]);
            AnaLabel.setText(String.valueOf(yeniSayiInt));
                } else if(IslemLabel.getText().contains("/")) {
                    yeniSayi = "";
            for (int i = 0; i < IslemLabel.getText().length() - 1; i++) {
            yeniSayi += IslemLabel.getText().charAt(i);
            }
             if (yeniSayi.length() > 8 || yeniSayiInt > 99999999) {
                        return;
                    }
            IslemLabel.setText(yeniSayi+ "/" + AnaLabel.getText() );
            islemDizisi = IslemLabel.getText().split("/");
            yeniSayiInt = Integer.valueOf(islemDizisi[0]) / Integer.valueOf(islemDizisi[1]);
            AnaLabel.setText(String.valueOf(yeniSayiInt));
                } else if(IslemLabel.getText().contains("-")) {
                    yeniSayi = "";
            for (int i = 0; i < IslemLabel.getText().length() - 1; i++) {
            yeniSayi += IslemLabel.getText().charAt(i);
            }
             if (yeniSayi.length() > 8 || yeniSayiInt > 99999999) {
                        return;
                    }
            IslemLabel.setText(yeniSayi+ "-" + AnaLabel.getText() );
            islemDizisi = IslemLabel.getText().split("-");
            yeniSayiInt = Integer.valueOf(islemDizisi[0]) - Integer.valueOf(islemDizisi[1]);
            AnaLabel.setText(String.valueOf(yeniSayiInt));
                } else if(IslemLabel.getText().contains("+")) {
                    yeniSayi = "";
            for (int i = 0; i < IslemLabel.getText().length() - 1; i++) {
            yeniSayi += IslemLabel.getText().charAt(i);
            }
             if (yeniSayi.length() > 8 || yeniSayiInt > 99999999) {
                        return;
                    }
            IslemLabel.setText(yeniSayi+ "+" + AnaLabel.getText() );
            islemDizisi = IslemLabel.getText().split("\\+");
            yeniSayiInt = Integer.valueOf(islemDizisi[0]) + Integer.valueOf(islemDizisi[1]);
            AnaLabel.setText(String.valueOf(yeniSayiInt));
                }
                
               yeniSayiInt = Integer.valueOf(islemDizisi[0]) * Integer.valueOf(islemDizisi[1]); 
               islemDizisi[0] = "0";
               islemDizisi[1] = "0";
            } else {
                if(IslemLabel.getText().contains("*")) {
                    islemDizisi = IslemLabel.getText().split("\\*");
                    islemDizisi[0] = AnaLabel.getText();
                    if (yeniSayiInt > 999999999 || islemDizisi[0].length() > 8 || islemDizisi[1].length() > 8) {
                        return;
                    }
                    IslemLabel.setText(islemDizisi[0] + "*" + islemDizisi[1]);
                    yeniSayiInt = Integer.valueOf(islemDizisi[0]) * Integer.valueOf(islemDizisi[1]);
                    AnaLabel.setText(String.valueOf(yeniSayiInt));
                } else if(IslemLabel.getText().contains("/")) {
                    islemDizisi = IslemLabel.getText().split("\\/");
                    islemDizisi[0] = AnaLabel.getText();
                    IslemLabel.setText(islemDizisi[0] + "/" + islemDizisi[1]);
                    if (yeniSayiInt > 999999999 || islemDizisi[0].length() > 8 || islemDizisi[1].length() > 8) {
                        return;
                    }
                    yeniSayiInt = Integer.valueOf(islemDizisi[0]) / Integer.valueOf(islemDizisi[1]);
                    AnaLabel.setText(String.valueOf(yeniSayiInt));
                } else if(IslemLabel.getText().contains("-")) {
                    islemDizisi = IslemLabel.getText().split("\\-");
                    islemDizisi[0] = AnaLabel.getText();
                    IslemLabel.setText(islemDizisi[0] + "-" + islemDizisi[1]);
                    if (yeniSayiInt > 999999999 || islemDizisi[0].length() > 8 || islemDizisi[1].length() > 8) {
                        return;
                    }
                    yeniSayiInt = Integer.valueOf(islemDizisi[0]) - Integer.valueOf(islemDizisi[1]);
                    AnaLabel.setText(String.valueOf(yeniSayiInt));
                } else if(IslemLabel.getText().contains("+")) {
                    islemDizisi = IslemLabel.getText().split("\\+");
                    islemDizisi[0] = AnaLabel.getText();
                    IslemLabel.setText(islemDizisi[0] + "+" + islemDizisi[1]);
                    if (yeniSayiInt > 999999999 || islemDizisi[0].length() > 8 || islemDizisi[1].length() > 8) {
                        return;
                    }
                    yeniSayiInt = Integer.valueOf(islemDizisi[0]) + Integer.valueOf(islemDizisi[1]);
                    AnaLabel.setText(String.valueOf(yeniSayiInt));
                }
                yeniSayiInt = 0;
                
                    islemDizisi[0] = "0";
                    
            }
            
        }
    }//GEN-LAST:event_EsittirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnaLabel;
    private javax.swing.JButton ArtiButton;
    private javax.swing.JButton ArtiEksiButton;
    private javax.swing.JButton BolButton;
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton CButton;
    private javax.swing.JButton CEButton;
    private javax.swing.JButton CarpButton;
    private javax.swing.JButton EksiButton;
    private javax.swing.JButton EsittirButton;
    private javax.swing.JLabel IslemLabel;
    private javax.swing.JButton SilButton;
    private javax.swing.JButton YuzdeButton;
    // End of variables declaration//GEN-END:variables
}
